<a href="https://colab.research.google.com/github/kimchangwoo1011/2020--2-AI/blob/master/05_minst-application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist
# mnist 데이터셋을 훈련과 테스트 데이터로 로드하여 준비
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)), 
  tf.keras.layers.Dense (128, activation='relu'), 
  tf.keras.layers.Dropout(.2), 
  tf.keras.layers. Dense (10, activation='softmax')
])


In [ ]:
model.compile(optimizer='adam',
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])
model.summary()
model.fit(x_train, y_train, epochs=5)
# 모델을 테스트 데이터로 평가 
model.evaluate(x_test, y_test)


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               100480    
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 2.3013 - accuracy: 0.1110
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 2.3008 - accuracy: 0.1128
Epoch 3/5
1875/1875 [=======================

[2.279986619949341, 0.1264999955892563]

In [ ]:
print(x_test[:1].shape)
pred_result = model.predict(x_test[:1])
print(pred_result.shape) 
print(pred_result)
print(pred_result[0])

(1, 28, 28)
(1, 10)
[[0.09061949 0.11682331 0.09780236 0.10407427 0.09672318 0.09012729
  0.09420386 0.10952536 0.09793561 0.10216527]]
[0.09061949 0.11682331 0.09780236 0.10407427 0.09672318 0.09012729
 0.09420386 0.10952536 0.09793561 0.10216527]


In [ ]:
import numpy as np

# 10 개의 수를 더하면? 
one_pred = pred_result[0] 
print(one_pred. sum())

# 혹시 가장 큰 수가 있는 첨자가 결과 
one = np.argmax(one_pred) 
print(one)


1.0
1


In [ ]:
import numpy as np

# 10 개의 수를 더하면? 
one_pred = pred_result[0] 
print(tf.reduce_sum (one_pred)) 
print(tf.reduce_sum(one_pred).numpy())
# 혹시 가장 큰 수가 있는 첨자가 결과 
print(tf.argmax(one_pred).numpy())


tf.Tensor(1.0, shape=(), dtype=float32)
1.0
1


In [ ]:
import numpy as np

print(np.argmax([5, 4, 10, 1, 2])) 
print(np.argmax([3, 1, 4, 9, 6, 7, 2]))  
print(np.argmax([[0.1,0.8. 0.1]. [10.7 0.2, 0.1], [0.2, 0.16 0.7]], axis=1))


2
3
[1 0 2]


In [ ]:
from random import sample 
import numpy as np

# x test로 직접 결과 처리 
pred_result = model.predict (x_test) 
print(pred_result.shape) 
print(pred_result[0]) 
print(np.argmax (pred_result[0]))

# 원핫 인코딩을 일반 데이터로 변환 
pred_labels = np.argmax (pred_result, axis=1) 
# 예측한 답 출력 
print(pred_labels) 
# 실제 정답 출력 
print(y_test)


(10000, 10)
[0.09061949 0.11682331 0.09780236 0.10407427 0.09672318 0.09012729
 0.09420386 0.10952536 0.09793561 0.10216527]
1
[1 1 1 ... 1 1 1]
[7 2 1 ... 4 5 6]


In [ ]:
from random import sample 
import numpy as np

pred_result = model.predict(x_test)
pred_labels = np.argmax(pred_result, axis=1)

nrows, ncols = 5, 4  
#출력 가로 세로 수 
samples = sorted(sample (range (len (x_test)), nrows * ncols))



NameError: ignored

In [ ]:
from random import sample 
import numpy as np

# 예측한 softmax의 확률이 있는 리스트 
pred_result = model.predict(x_test)
pred_labels = np.argmax(pred_result, axis=1)

samples = sorted(sample(range(len(x_test)), nrows * ncols))

count = 0 
nrows, ncols = 5, 4 
plt.figure(figsize=(12,10)) 
for n in samples:
  count += 1 
  plt.subplot (nrows, ncols, count) 
  # 예측이 틀린 것은 파란색으로 그리기 
  cmap = 'Greys' if ( pred_labels[n] == y_test[n]) else 'Blues' 
  plt.imshow(x_test[n].reshape (28, 28), cmap=cmap, interpolation='nearest') 
  tmp = "Label:" + str(y_test[n]) + ", Prediction:" + str (pred_labels [n]) 
  plt.title (tmp)

  plt.tight_layout() 
  plt.show()

NameError: ignored

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), 
    tf.keras.layers.Dense(128, activation='relu'), 
    tf.keras.layers.Dropout(.2), 
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dropout (.2), 
    tf.keras.layers.Dense(10, activation='softmax')

])
model.compile(optimizer='adam',
                 loss='sparse_categorical_crossentropy', 
                  metrics=['accuracy'])
model.summary()

model.fit(x_train, y_train, epochs=20)


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 128)               100480    
_________________________________________________________________
dropout_4 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout_5 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 10)                650       
Total params: 109,386
Trainable params: 109,386
Non-trainable params: 0
________________________________________________

In [ ]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist
 (x_train, y_train), (x_test, y_test) = mnist.load_data()
 x_train, x_test = x_train / 255.0, x test / 255.0 
 x_train = x_train.reshape((60000, 28~28)) 
  x_test.= x_test.reshape((1,0000, 28 *28))

  model = tf.keras.models.Sequential([
            tf.keras.layers.Dense(128, activation='relu', input_shape=(28 * 28,)),
            tf.keras.layers.Dropout(0.2), 
            tf.keras.layers.Dense(10, activation='softmax')
  ])
model.summary()
model.compile(optimizer='adam',
              loss='sparse categorical_crossentropy', 
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5) 
model.evaluate(x_test, y_test)

IndentationError: ignored